//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlytrotdmune.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMO2
    {
        public int IDDEMO { get; set; }
        public string DEMO { get; set; }
    }
}
