//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlytrotdmune.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        public int image_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string url { get; set; }
    
        public virtual ROOM ROOM { get; set; }
    }
}
